'?':
    value: false
_wandb:
    value:
        cli_version: 0.28.0
        e:
            o5j0egc45332u26vobqa4mmbzzj1od17:
                args:
                    - --env_name=mountaincar-human-v0
                    - --expectile
                    - "0.5"
                    - --seed
                    - "3"
                codePath: train/train_LEQ.py
                codePathLocal: train/train_LEQ.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1966736678912"
                        used: "1384229105664"
                email: mohammad200h@hotmail.com
                executable: /usr/bin/python3
                git:
                    remote: git@github.com:mohammad200h/LEQ.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-bf0b8999-a9f8-10ee-5cfe-831ec7f4c565
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-9e5e2fab-4ec0-68a7-c2f5-0ddaf9e6b93d
                host: mamaad
                memory:
                    total: "67249684480"
                os: Linux-6.17.0-40-generic-x86_64-with-glibc2.35
                program: /workspace/LEQ/train/train_LEQ.py
                python: CPython 3.10.12
                root: /workspace/LEQ
                startedAt: "2026-07-16T14:31:28.810133Z"
                writerId: o5j0egc45332u26vobqa4mmbzzj1od17
        m:
            - "1": training/step
              "6":
                - 3
              "7": []
            - "1": evaluation/step
              "6":
                - 3
              "7": []
            - "2": training/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": evaluation/*
              "5": 2
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 7
                - 13
                - 16
            "4": 3.10.12
            "5": 0.28.0
            "12": 0.28.0
            "13": linux-x86_64
actor_lr:
    value: 3e-05
actor_update:
    value: lambda-return
alsologtostderr:
    value: false
batch_size:
    value: 256
chex_assert_multiple_cpu_devices:
    value: false
chex_n_cpu_devices:
    value: 1
chex_skip_pmap_variant_if_single_device:
    value: true
config:
    value: |
        actor_lr: 3.0e-05
        critic_lr: 0.0001
        dropout_rate: null
        model_hidden_dims: !!python/tuple
        - 200
        - 200
        - 200
        - 200
        model_lr: 0.0003
        num_elites: 5
        num_models: 7
        value_lr: 0.0001
critic_lr:
    value: 0.0001
critic_update:
    value: lambda-return
debug:
    value: false
discount:
    value: 0.997
dropout_rate:
    value: null
dynamics:
    value: torch
env_name:
    value: mountaincar-human-v0
eval_episodes:
    value: 10
eval_interval:
    value: 50000
expectile:
    value: 0.5
help:
    value: false
helpfull:
    value: false
helpshort:
    value: false
helpxml:
    value: false
horizon_length:
    value: 10
lamb:
    value: 0.95
layer_size:
    value: 256
load_dir:
    value: null
log_dir:
    value: ""
log_interval:
    value: 10000
logtostderr:
    value: false
maintain_model:
    value: false
max_steps:
    value: 1000000
model_batch_ratio:
    value: 0.25
model_hidden_dims:
    value:
        - 200
        - 200
        - 200
        - 200
model_lr:
    value: 0.0003
no_rollout:
    value: false
num_elites:
    value: 5
num_layers:
    value: 3
num_models:
    value: 7
num_repeat:
    value: 1
only_check_args:
    value: false
only_check_flags:
    value: false
pdb:
    value: false
pdb_post_mortem:
    value: false
pretrain:
    value: false
profile_file:
    value: null
rollout_batch_size:
    value: 50000
rollout_freq:
    value: 1000
rollout_length:
    value: 5
rollout_retain:
    value: 5
run_with_pdb:
    value: false
run_with_profiling:
    value: false
save_dir:
    value: ./tmp/EP/
save_interval:
    value: 100000
seed:
    value: 3
showprefixforinfo:
    value: true
stderrthreshold:
    value: fatal
test_random_seed:
    value: 301
test_randomize_ordering_seed:
    value: ""
test_srcdir:
    value: ""
test_tmpdir:
    value: /tmp/absl_testing
use_cprofile_for_profiling:
    value: true
v:
    value: 0
value_lr:
    value: 0.0001
verbosity:
    value: 0
video_interval:
    value: 50000
wandb_key:
    value: ""
xml_output_file:
    value: ""
